PROYECTO-TOO/Gestion_Proyectos/Controllers/ActividadController.cs
using CapaDatos;
using CapaEntidad;
using Gestion_Proyectos.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gestion_Proyectos.Controllers
{
    public class ActividadController : Controller
    {
        [ValidarSesion]
        // GET: Actividad
        public ActionResult VistaActividad(int? idProyecto)

        {
            if (idProyecto.HasValue)
            {
                // Obtener objetivos relacionados con el proyecto según el idProyecto
                List<Actividad> listaActividad = new GestionActividades().GetActividadesPorProyecto(idProyecto.Value);
                return View(listaActividad);
            }
            else
            {
                // Si no se proporciona un valor para idProyecto, se generará una excepción y se redirigirá a la vista de error personalizada.
                return RedirectToAction("Index", "Home");
            }

        }
        //
        [HttpGet]
        public JsonResult ListarActividadesPorProyecto(int idProyecto)
        {
            List<Actividad> listaActividad = new List<Actividad>();
            listaActividad = new GestionActividades().GetActividadesPorProyecto(idProyecto);
            return Json(new { data = listaActividad }, JsonRequestBehavior.AllowGet);
        }
        //
        [HttpPost]
        public JsonResult AgregarActividad(Actividad Act)
        {
            if (ModelState.IsValid)
            {
                GestionActividades gestionActividades = new GestionActividades();

                bool insercionExitosa = gestionActividades.newActividad(Act);

                if (insercionExitosa)
                {
                    return Json(new { success = true, message = "Actividad insertado exitosamente" });
                }
                else
                {
                    return Json(new { success = false, message = "Error al insertar la actividad" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }
        //
        [HttpPost]
        public JsonResult EditarActividad(Actividad act)
        {
            if (ModelState.IsValid)
            {
                GestionActividades gestionActividades = new GestionActividades();

                bool actualizacionExitosa = gestionActividades.EditActividad(act);

                if (actualizacionExitosa)
                {
                    return Json(new { success = true, message = "Actividad actualizada exitosamente" });
                }
                else
                {
                    return Json(new { success = false, message = "Error al actualizar la actividad" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }
        //
        [HttpPost]
        public JsonResult BorrarActividad(int idActividad)
        {
            GestionActividades gestionActividades = new GestionActividades();

            bool eliminacionExitosa = gestionActividades.EliminarActividad(idActividad);

            if (eliminacionExitosa)
            {
                return Json(new { success = true, message = "Actividad eliminada exitosamente" });
            }
            else
            {
                return Json(new { success = false, message = "Error al eliminar la actividad" });
            }
        }

    }
}

PROYECTO-TOO/Gestion_Proyectos/Controllers/TareaController.cs
using CapaDatos;
using CapaEntidad;
using Gestion_Proyectos.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gestion_Proyectos.Controllers
{
    public class TareaController : Controller
    {
        [ValidarSesion]
        // GET: Tarea
        public ActionResult VistaTarea(int? idActividad)
        {
            if (idActividad.HasValue)
            {
                // Obtener objetivos relacionados con el proyecto según el idProyecto
                List<Tarea> listaTarea = new GestionTareas().GetTareasPorActividad(idActividad.Value);
                return View(listaTarea);
            }
            else
            {
                // Si no se proporciona un valor para idProyecto, se generará una excepción y se redirigirá a la vista de error personalizada.
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public JsonResult ListarTareasPorActividad(int IDACTIVIDAD)
        {
            List<Tarea> listaTarea = new List<Tarea>();
            listaTarea = new GestionTareas().GetTareasPorActividad(IDACTIVIDAD);
            return Json(new { data = listaTarea }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AgregarTarea(Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                GestionTareas gestionTareas = new GestionTareas();

                if (tarea.fechaFinT >= tarea.fechaIniT)
                {
                    bool insercionExitosa = gestionTareas.RegistrarTarea(tarea);

                    if (insercionExitosa)
                    {
                        return Json(new { success = true, message = "Tarea insertada exitosamente" });
                    }
                    else
                    {
                        return Json(new { success = false, message = "Error al insertar la tarea" });
                    }
                }
                else
                {
                    return Json(new { success = false, message = "La fecha de finalización no puede ocurrir antes que la fecha de inicio" });
                }

            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }

        [HttpPost]
        public JsonResult EditarTarea(Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                if (tarea.fechaFinT >= tarea.fechaIniT)
                {
                    GestionTareas gestionTareas = new GestionTareas();

                    bool actualizacionExitosa = gestionTareas.EditarTarea(tarea);

                    if (actualizacionExitosa)
                    {
                        return Json(new { success = true, message = "Tarea actualizada exitosamente" });
                    }
                    else
                    {
                        return Json(new { success = false, message = "Error al actualizar la tarea" });
                    }
                }
                else
                {
                    return Json(new { success = false, message = "La fecha de finalización no puede ocurrir antes que la fecha de inicio" });
                }

            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }

        [HttpPost]
        public JsonResult EliminarTarea(int idTarea)
        {
            GestionTareas gestionTareas = new GestionTareas();

            bool eliminacionExitosa = gestionTareas.EliminarTarea(idTarea);

            if (eliminacionExitosa)
            {
                return Json(new { success = true, message = "Proyecto eliminado exitosamente" });
            }
            else
            {
                return Json(new { success = false, message = "Error al eliminar el proyecto" });
            }
        }
    }
}

PROYECTO-TOO/Gestion_Proyectos/Views/Actividad/VistaActividad.cshtml
@{
    ViewBag.Title = "VistaActividad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        #tablaActividades {
            border-collapse: collapse;
            width: 100%;
        }

            #tablaActividades th, #tablaActividades td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }

            #tablaActividades th {
                background-color: #f2f2f2;
            }

            #tablaActividades tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #tablaActividades tr:hover {
                background-color: #ddd;
            }

            /* Alineación de los botones en cada fila */
            #tablaActividades .btn {
                margin-right: 5px; /* Espacio entre botones */
            }

            /* Ajuste de z-index para que los botones no se superpongan con el contenido de la fila */
            #tablaActividades .show-control {
                z-index: 2;
            }
    </style>
</head>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary mt-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Nueva Actividad
</button>

<!-- Modal  de actividades-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Nueva Actividad</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="modalForm">

                    <div class="card-body">
                        <div class="form-group">
                            <label for="descripcion">Titulo</label>
                            <textarea class="form-control" id="nombreAct" name="nombreAct" placeholder="Ingrese el nombre de la actividad del proyecto" required></textarea>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="descripcion">Descripción</label>
                            <textarea class="form-control" id="descripcionAct" name="descripcionAct" placeholder="Ingrese una descripción de la actividad del proyecto" required></textarea>
                        </div>
                    </div>

                    <!-- /.card-body -->


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar actividad</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="modalForm" method="post">

                    <div class="card-body">

                        <div class="card-body">
                            <div class="form-group">
                                <label for="descripcion">Descripción</label>
                                <textarea class="form-control" id="nombreAct1" name="nombreAct" placeholder="Ingrese el nombre de la actividad del proyecto" required></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="descripcion">Descripción</label>
                            <textarea class="form-control" id="descripcionAct1" name="descripcionAct" placeholder="Ingrese una descripción del proyecto" required></textarea>
                        </div>
                        <input type="hidden" id="editIdActividad" value="">


                    </div>

                    <!-- /.card-body -->


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary" onclick="Editar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header">
        <h3 class="card-title">Lista de Actividades</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-3">
        <table id="tablaActividades">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th></th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
    <!-- /.card-body -->
</div>

@section scripts {
    <script>

        var tablaActividad;
        var info;
        var id = GetURLParameter('idProyecto');
        function GetURLParameter(sParam) {
            var sPageURL = window.location.search.substring(1);
            var sURLVariables = sPageURL.split('&');
            for (var i = 0; i < sURLVariables.length; i++) {
                var sParameterName = sURLVariables[i].split('=');
                if (sParameterName[0] == sParam) {
                    console.log(sParameterName[1]);
                    return sParameterName[1];
                }
            }
            return null;
        }
        function Guardar() {
            // Evita la acción predeterminada del formulario (recargar la página).
            console.log(id);
            var Actividad = {
                nombreAct: $("#nombreAct").val(),
                descripcionAct: $("#descripcionAct").val(),
                idProyecto: id

            }

            $.ajax({
                url: "@Url.Action("AgregarActividad", "Actividad")",
                type: "POST",
                data: JSON.stringify(Actividad), // No necesitas envolverlo en un objeto { Proyecto: proyecto }
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // Aquí puedes manejar la respuesta del servidor, como mostrar un mensaje de éxito o error.
                    if (data.success) {

                        $("#exampleModal").modal("hide"); // Cierra el modal
                        tablaActividad.ajax.reload();
                        // Aquí puedes recargar la tabla u otra actualización si es necesario.
                    } else {
                        alert("Error: " + data.message); // Muestra un mensaje de error
                    }
                }
            });
        }
        function Editar() {

                // Obtén los datos del formulario de edición
                var ActividadEditada = {
                    idActividad: $("#editIdActividad").val(),
                    nombreAct: $("#nombreAct1").val(),
                    descripcionAct: $("#descripcionAct1").val(),
                    // Asegúrate de incluir el ID del proyecto que se está editando

                };

                jQuery.ajax({
                    url: "@Url.Action("EditarActividad", "Actividad")",
                    type: "POST",
                    data: JSON.stringify(ActividadEditada),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.success) {
                            $("#exampleModal2").modal("hide"); // Cierra el modal de edición
                            tablaActividad.ajax.reload();
                        } else {
                            alert("Error al actualizar el Actividad: " + data.message);
                        }
                    }
                });

        }
        $(document).ready(function () {

            $('#exampleModal').on('show.bs.modal', function () {
                // Restablecer los campos del modal
                $("#nombreAct").val("");
                $("#descripcionAct").val("");


            });

            tablaActividad = $('#tablaActividades').DataTable({
                responsive: true,
                autoWidth: false,
                ordering: false,
                "ajax": {
                    url: '@Url.Action("ListarActividadesPorProyecto", "Actividad")' + '?idProyecto=' + GetURLParameter('idProyecto'), // URL para obtener objetivos relacionados con el proyecto
                    data: function (data) {
                        data = id;
                    },
                    type: "GET",
                    dataType: "json",
                },
                "columns": [

                    { "data": "nombreAct", "type": "auto" },
                    { "data": "descripcionAct", "type": "auto" },


                    {
                        "data": null,
                        "render": function (data, type, row) {
                            // Botón de edición en la fila principal de datos
                            var editarBtn = '<button class="btn btn-primary btn-editar" data-idActividad="' + row.id + '"><i class="fas fa-pen"></i></button>';
                            var borrarBtn = '<button class="btn btn-danger btn-borrar" data-idActividad="' + row.id + '"><i class="fas fa-trash"></i></button>';

                            return editarBtn + borrarBtn;
                        }
                    },
                    {
                        "data": "idActividad", // Asegúrate de ajustar el nombre de la propiedad que contiene el ID del proyecto
                        "render": function (data, type, row) {
                            var verTareasBtn = '<button class="btn btn-info btn-ver-Tareas" data-idActividad="' + data + '">Tareas</button>';
                            return verTareasBtn;
                        }
                    },


                    // Agrega más columnas según tus necesidades
                ],
                "language": {
                    url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/es-ES.json',
                }
            });
            $('#tablaActividades tbody').on('click', '.btn-ver-Tareas', function ()
            {
                var filaSeleccionada = $(this).closest("tr");
                info = tablaActividad.row(filaSeleccionada).data();
                var idProyecto = info.idProyecto;
                var idActividad = info.idActividad;
                console.log(idProyecto);
                console.log(idActividad);
                // Redirige al usuario a la VistaObjetivo con el idProyecto
                window.location.href = '@Url.Action("VistaTarea", "Tarea")' + '?idActividad=' + idActividad;
            });



            $('#tablaActividades tbody').on('click', '.btn-editar', function () {
                var filaSeleccionada = $(this).closest("tr");
                info = tablaActividad.row(filaSeleccionada).data();
                console.log(info);
                //elementos ocultos

                $("#editIdActividad").val(info.idActividad);
                $("#nombreAct1").val(info.nombreAct);
                $("#descripcionAct1").val(info.descripcionAct)

                $("#exampleModal2").modal("show");

            });
            $('#tablaActividades').on('click', '.btn-borrar', function () {

                var objSeleccionado = $(this).closest("tr");
                var info2 = tablaActividad.row(objSeleccionado).data();
                swal({
                    title: "Estas seguro?",
                    text: "Deseas eliminar la actividad?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Si!",
                    cancelButtonText: "No",
                    closeOnConfirm: true
                },
                    function () {

                            jQuery.ajax({
                                url: "@Url.Action("BorrarActividad", "Actividad")",
                                type: "POST",
                                data: JSON.stringify({ idActividad: info2.idActividad }),
                                dataType: "json",
                                contentType: "application/json; charset=utf-8",
                                success: function (data) {
                                    if (data.success) {

                                        // Recargar la tabla después de eliminar el proyecto
                                        tablaActividad.ajax.reload();
                                    } else {
                                        swal("Error", "Error al eliminar la actividad: " + data.message, "error");
                                    }
                                }
                            });

                    });

            });




        });
    </script>
}