PROYECTO-TOO/Gestion_Proyectos/Controllers/AsignacionController.cs
using CapaDatos;
using CapaEntidad;
using Gestion_Proyectos.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gestion_Proyectos.Controllers
{
    public class AsignacionController : Controller
    {
        [ValidarSesion]
        // GET: Asignacion
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MisTareas()
        {
            // Obtén el usuario actual desde la sesión
            Usuario user = Session["usuario"] as Usuario;
            GestionAsignaciones gestionAsignaciones = new GestionAsignaciones();
            if (user != null)
            {
                List<Tarea> tareasAsignadas = gestionAsignaciones.ObtenerTareasAsignadas(user.id);

                return View(tareasAsignadas);
            }
            else
            {
                // El usuario no ha iniciado sesión, redirige o muestra un mensaje de error
                return RedirectToAction("Index","Home"); // O una vista de error
            }
        }
        [HttpGet]
        public JsonResult ListarTareasAsignadas()
        {
            if (Session["usuario"] != null)
            {
                Usuario usuario = (Usuario)Session["usuario"];
                List<Tarea> listaTareas = ObtenerAsignadas(usuario.id);

                return Json(new { data = listaTareas }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                // Si el usuario no ha iniciado sesión, retorna un JSON vacío o un mensaje de error.
                return Json(new { data = new List<Tarea>() }, JsonRequestBehavior.AllowGet);
            }
        }
        private List<Tarea> ObtenerAsignadas(int usuarioId)
        {
            return new GestionAsignaciones().ObtenerTareasAsignadas(usuarioId);
        }


        public JsonResult BuscarUsuarioPorCorreo(string correoUsuario)
        {
            GestionUsuarios gestionUsuario = new GestionUsuarios();
            Usuario usuario = gestionUsuario.ObtenerUsuarioPorCorreo(correoUsuario);

            if (usuario != null)
            {
                // Usuario encontrado, puedes devolver los datos del usuario como JSON
                return Json(new { success = true, nombre = usuario.nombre, apellido = usuario.apellido, correo = usuario.correo }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                // Usuario no encontrado, devolver un mensaje de error
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult AsignarTarea(int idTarea, string usuarioCorreo)
        {
            try
            {
                // Primero, verifica si el usuario con el correo proporcionado existe en la base de datos
                GestionUsuarios gestionUsuario = new GestionUsuarios();
                Usuario usuario = gestionUsuario.ObtenerUsuarioPorCorreo(usuarioCorreo);


                // Si el usuario existe, puedes realizar la asignación de tarea
                GestionAsignaciones gestionAsignaciones = new GestionAsignaciones();
                bool asignacionExistente = gestionAsignaciones.ExisteAsignacion(idTarea);

                if (asignacionExistente)
                {
                    // La tarea ya está asignada al usuario, devuelve un mensaje de error
                    return Json(new { success = false, message = "La tarea ya está asignada." }, JsonRequestBehavior.AllowGet);
                }

                bool asignacionExitosa = gestionAsignaciones.newAsignacion(usuario.id, idTarea);

                if (asignacionExitosa)
                {
                    // Tarea asignada con éxito
                    return Json(new { success = true, message = "Tarea asignada con éxito." }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    // Ocurrió un error durante la asignación, muestra un mensaje de error
                    return Json(new { success = false, message = "Error al asignar la tarea." }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                // Manejo de excepciones
                return Json(new { success = false, message = "Error: " + ex.Message, stackTrace = ex.StackTrace }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

PROYECTO-TOO/Gestion_Proyectos/Controllers/ProyectoController.cs
using CapaDatos;
using CapaEntidad;
using Gestion_Proyectos.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;


namespace Gestion_Proyectos.Controllers
{
    [ValidarSesion]
    public class ProyectoController : Controller
    {
        // GET: Proyecto
        public ActionResult VistaProyecto()
        {
            return View();
        }
        public ActionResult VistaObjetivo()
        {
            return View();
        }

        /*
        public ActionResult VistaActividad()
        {
            return View();
        }
        */
        public ActionResult VistaTarea()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ListarProyectos()
        {
            if (Session["usuario"] != null)
            {
                Usuario usuario = (Usuario)Session["usuario"];
                List<Proyecto> listaProyectos = ObtenerProyectosPorUsuario(usuario.id);

                return Json(new { data = listaProyectos }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                // Si el usuario no ha iniciado sesión, retorna un JSON vacío o un mensaje de error.
                return Json(new { data = new List<Proyecto>() }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult ListarEventos()
        {
            if (Session["usuario"] != null)
            {
                Usuario usuario = (Usuario)Session["usuario"];
                List<Proyecto> listaProyectos = ObtenerProyectosPorUsuario(usuario.id);

                // Crear una lista de eventos con fechas de inicio, finalización y color
                var eventos = listaProyectos.Select((proyecto, index) => new
                {
                    title = proyecto.nombreProyecto,
                    
                    start = proyecto.fechaIni.ToString("yyyy-MM-dd"), // Fecha de inicio
                    end = proyecto.fechaFin.ToString("yyyy-MM-dd"), // Fecha de finalización
                    color = ObtenerColorEvento(index) // Función para obtener colores diferentes
                }).ToList();

                return Json(eventos, JsonRequestBehavior.AllowGet);
            }
            else
            {
                // Si el usuario no ha iniciado sesión, retorna un JSON vacío o un mensaje de error.
                return Json(new List<object>(), JsonRequestBehavior.AllowGet);
            }
        }

        private string[] coloresEventos = { "#FF5733", "#5F9EA0", "#5733FF", "#E9967A", "#33B3FF" }; // Lista de colores

        private string ObtenerColorEvento(int index)
        {
            // Asigna colores de manera cíclica a los eventos
            return coloresEventos[index % coloresEventos.Length];
        }



        private List<Proyecto> ObtenerProyectosPorUsuario(int usuarioId)
        {
            return new GestionProyectos().GetProyectos(usuarioId);
        }


        [HttpPost]
        public JsonResult AgregarProyecto(Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                GestionProyectos gestionProyectos = new GestionProyectos();

                // Obtén el usuario actual de la sesión
                Usuario usuarioActual = (Usuario)Session["usuario"];

                if (usuarioActual != null)
                {
                    // Asigna el ID del usuario al proyecto
                    if (proyecto.fechaFin >= proyecto.fechaIni)
                    {
                        bool insercionExitosa = gestionProyectos.newProyecto(proyecto, usuarioActual.id);

                        if (insercionExitosa)
                        {
                            return Json(new { success = true, message = "Proyecto insertado exitosamente" });
                        }
                        else
                        {
                            return Json(new { success = false, message = "Error al insertar el proyecto" });
                        }
                    }
                    else
                    {
                        return Json(new { success = false, message = "La fecha de finalización no puede ser anterior a la fecha de inicio" });
                    }
                    
                }
                else
                {
                    return Json(new { success = false, message = "Usuario no encontrado en la sesión" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }

        [HttpPost]
        public JsonResult EditarProyecto(Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                if (proyecto.fechaFin >= proyecto.fechaIni)
                {
                    GestionProyectos gestionProyectos = new GestionProyectos();

                    bool actualizacionExitosa = gestionProyectos.EditProyecto(proyecto);

                    if (actualizacionExitosa)
                    {
                        return Json(new { success = true, message = "Proyecto actualizado exitosamente" });
                    }
                    else
                    {
                        return Json(new { success = false, message = "Error al actualizar el proyecto" });
                    }
                }
                else
                {
                    return Json(new { success = false, message = "La fecha de finalización no puede ser anterior a la fecha de inicio" });
                }
                
            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }
        [HttpPost]
        public JsonResult BorrarProyecto(int idProyecto)
        {
            GestionProyectos gestionProyectos = new GestionProyectos();

            bool eliminacionExitosa = gestionProyectos.EliminarProyecto(idProyecto);

            if (eliminacionExitosa)
            {
                return Json(new { success = true, message = "Proyecto eliminado exitosamente" });
            }
            else
            {
                return Json(new { success = false, message = "Error al eliminar el proyecto" });
            }
        }


    }
}

PROYECTO-TOO/Gestion_Proyectos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")


    <style>
        .navbar-nav li a {
            color: gray;
            text-decoration: none;
        }

            .navbar-nav li a:hover {
                color: white; /* Cambia a tu color deseado al pasar el ratón */
            }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                locale: 'es',
                events: {
                    url: '@Url.Action("ListarEventos", "Proyecto")',
                    method: 'GET',
                    failure: function () {
                        // Manejar errores en la solicitud AJAX
                    }
                }

            });
            calendar.render();
        });
    </script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index", "Home")">Proyecto TOO-115</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                
            </ul>
            
        </div>
        <!--form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Buscar..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </!--form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" >@Session["correo"]</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion", "Acceso")">Cerrar Sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Gestión</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-sitemap"></i></div>
                            PROYECTOS
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("VistaProyecto", "Proyecto")">Proyectos</a>
                                
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" href="@Url.Action("MisTareas", "Asignacion")">
                                    Asignaciones
                                </a>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading"></div>
                        
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Bienvenido:</div>
                    @if (Session["nombre"] != null )
                    {
                        <p>@Session["nombre"] @Session["apellido"]</p>
                    }

                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Proyecto TOO-115 2023</div>
                        
                    </div>
                </div>
            </footer>
        </div>
    </div>
            
    
        
        
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>