PROYECTO-TOO/Gestion_Proyectos/Controllers/ObjetivoController.cs
using CapaDatos;
using CapaEntidad;
using Gestion_Proyectos.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gestion_Proyectos.Controllers
{
    [ValidarSesion]
    public class ObjetivoController : Controller
    {
        // GET: Objetivo
        public ActionResult VistaObjetivo(int? idProyecto)
        {
            if (idProyecto.HasValue)
            {
                // Obtener objetivos relacionados con el proyecto según el idProyecto
                List<Objetivo> listaObjetivos = new GestioObjetivos().GetObjetivosPorProyecto(idProyecto.Value);
                return View(listaObjetivos);
            }
            else
            {
                // Si no se proporciona un valor para idProyecto, se generará una excepción y se redirigirá a la vista de error personalizada.
                return RedirectToAction("Index","Home");
            }
        }

        [HttpGet]
        public JsonResult ListarObjetivos()
        {
            List<Objetivo> listaObjetivos = new List<Objetivo>();
            listaObjetivos = new GestioObjetivos().GetObjetivos();
            return Json(new { data = listaObjetivos }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult AgregarObjetivo(Objetivo objetivo)
        {
            if (ModelState.IsValid)
            {
                GestioObjetivos gestionObjetivos = new GestioObjetivos();

                bool insercionExitosa = gestionObjetivos.newObjetivo(objetivo);

                if (insercionExitosa)
                {
                    return Json(new { success = true, message = "Objetivo insertado exitosamente" });
                }
                else
                {
                    return Json(new { success = false, message = "Error al insertar el Objetivo" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }
        [HttpPost]
        public JsonResult EditarObjetivo(Objetivo objetivo)
        {
            if (ModelState.IsValid)
            {
                GestioObjetivos gestionObjetivos = new GestioObjetivos();

                bool actualizacionExitosa = gestionObjetivos.EditObjetivo(objetivo);

                if (actualizacionExitosa)
                {
                    return Json(new { success = true, message = "Objetivo actualizado exitosamente" });
                }
                else
                {
                    return Json(new { success = false, message = "Error al actualizar el Objetivo" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Por favor, complete todos los campos obligatorios correctamente" });
            }
        }
        [HttpPost]
        public JsonResult BorrarObjetivo(int idObjetivo)
        {
            GestioObjetivos gestionObjetivos = new GestioObjetivos();

            bool eliminacionExitosa = gestionObjetivos.EliminarObjetivo(idObjetivo);

            if (eliminacionExitosa)
            {
                return Json(new { success = true, message = "Objetivo eliminado exitosamente" });
            }
            else
            {
                return Json(new { success = false, message = "Error al eliminar el Objetivo" });
            }
        }
        [HttpGet]
        public JsonResult ListarObjetivosPorProyecto(int idProyecto)
        {
            List<Objetivo> listaObjetivos = new List<Objetivo>();
            listaObjetivos = new GestioObjetivos().GetObjetivosPorProyecto(idProyecto);
            return Json(new { data = listaObjetivos }, JsonRequestBehavior.AllowGet);
        }

    }
}

PROYECTO-TOO/Gestion_Proyectos/Views/Objetivo/VistaObjetivo.cshtml
@{
    ViewBag.Title = "VistaObjetivo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        #tablaObjetivos {
            border-collapse: collapse;
            width: 100%;
        }

            #tablaObjetivos th, #tablaObjetivos td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }

            #tablaObjetivos th {
                background-color: #f2f2f2;
            }

            #tablaObjetivos tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #tablaObjetivos tr:hover {
                background-color: #ddd;
            }

            /* Alineación de los botones en cada fila */
            #tablaObjetivos .btn {
                margin-right: 5px; /* Espacio entre botones */
            }

            /* Ajuste de z-index para que los botones no se superpongan con el contenido de la fila */
            #tablaObjetivos .show-control {
                z-index: 2;
            }
    </style>
</head>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary mt-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Nuevo Objetivo
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Nuevo Objetivo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="modalForm">

                    <div class="card-body">
                        <div class="form-group">
                            <label for="descripcion">Descripción</label>
                            <textarea class="form-control" id="descripcionObj" name="descripcionObj" placeholder="Ingrese una descripción del Objetivo del proyecto" required></textarea>
                        </div>
                    </div>

                    <!-- /.card-body -->


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Objetivo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="modalForm" method="post">

                    <div class="card-body">
                        
                        <div class="form-group">
                            <label for="descripcion">Descripción</label>
                            <textarea class="form-control" id="descripcionObj1" name="descripcionObj" placeholder="Ingrese una descripción del proyecto" required></textarea>
                        </div>
                        <input type="hidden" id="editIdObjetivo" value="">
                        

                    </div>

                    <!-- /.card-body -->


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary" onclick="Editar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header">
        <h3 class="card-title">Lista de Objetivos</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-3">
        <table id="tablaObjetivos">
            <thead>
                <tr>
                    <th>Descripción</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
    <!-- /.card-body -->
</div>

@section scripts {
    <script>

        var tablaObjetivo;
        var info;
        var id = GetURLParameter('idProyecto');

        function GetURLParameter(sParam) {
            var sPageURL = window.location.search.substring(1);
            var sURLVariables = sPageURL.split('&');
            for (var i = 0; i < sURLVariables.length; i++) {
                var sParameterName = sURLVariables[i].split('=');
                if (sParameterName[0] == sParam) {
                    return sParameterName[1];
                }
            }
            return null;
        }
        function Guardar() {
            // Evita la acción predeterminada del formulario (recargar la página).
            console.log(id);
            var objetivo = {
                descripcionObj: $("#descripcionObj").val(),
                idPro: {
                    idProyecto: id
                }
            }

            $.ajax({
                url: "@Url.Action("AgregarObjetivo", "Objetivo")",
                type: "POST",
                data: JSON.stringify(objetivo), // No necesitas envolverlo en un objeto { Proyecto: proyecto }
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // Aquí puedes manejar la respuesta del servidor, como mostrar un mensaje de éxito o error.
                    if (data.success) {

                        $("#exampleModal").modal("hide"); // Cierra el modal
                        tablaObjetivo.ajax.reload();
                        // Aquí puedes recargar la tabla u otra actualización si es necesario.
                    } else {
                        alert("Error: " + data.message); // Muestra un mensaje de error
                    }
                }
            });
        }
        function Editar() {

                // Obtén los datos del formulario de edición
                var objetivoEditado = {
                    idObjetivo: $("#editIdObjetivo").val(),
                    descripcionObj: $("#descripcionObj1").val(),
                    // Asegúrate de incluir el ID del proyecto que se está editando

                };

                jQuery.ajax({
                    url: "@Url.Action("EditarObjetivo", "Objetivo")",
                    type: "POST",
                    data: JSON.stringify(objetivoEditado),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.success) {
                            $("#exampleModal2").modal("hide"); // Cierra el modal de edición
                            tablaObjetivo.ajax.reload();
                        } else {
                            alert("Error al actualizar el Objetivo: " + data.message);
                        }
                    }
                });

        }
        $(document).ready(function () {

            $('#exampleModal').on('show.bs.modal', function () {
                // Restablecer los campos del modal
                $("#descripcionObj").val("");


            });

            tablaObjetivo = $('#tablaObjetivos').DataTable({
                responsive: true,
                autoWidth: false,
                ordering: false,
                "ajax": {
                    url: '@Url.Action("ListarObjetivosPorProyecto", "Objetivo")' + '?idProyecto=' + GetURLParameter('idProyecto'), // URL para obtener objetivos relacionados con el proyecto
                    data: function (data) {
                        data = id;
                    },
                    type: "GET",
                    dataType: "json",
                },
                "columns": [

                    { "data": "descripcionObj", "type": "auto" },

                    {
                        "data": null,
                        "render": function (data, type, row) {
                            // Botón de edición en la fila principal de datos
                            var editarBtn = '<button class="btn btn-primary btn-editar" data-idObjetivo="' + row.id + '"><i class="fas fa-pen"></i></button>';
                            var borrarBtn = '<button class="btn btn-danger btn-borrar" data-idObjetivo="' + row.id + '"><i class="fas fa-trash"></i></button>';

                            return editarBtn + borrarBtn;
                        }
                    }


                    // Agrega más columnas según tus necesidades
                ],
                "language": {
                    url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/es-ES.json',
                }
            });


            $('#tablaObjetivos tbody').on('click', '.btn-editar', function () {
                var filaSeleccionada = $(this).closest("tr");
                info = tablaObjetivo.row(filaSeleccionada).data();
                console.log(info);
                //elementos ocultos
                $("#editIdObjetivo").val(info.idObjetivo);
                $("#descripcionObj1").val(info.descripcionObj)

                $("#exampleModal2").modal("show");

            });
            $('#tablaObjetivos').on('click', '.btn-borrar', function () {

                var objSeleccionado = $(this).closest("tr");
                var info2 = tablaObjetivo.row(objSeleccionado).data();
                swal({
                    title: "Estas seguro?",
                    text: "Deseas eliminar el Objetivo?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Si!",
                    cancelButtonText: "No",
                    closeOnConfirm: true
                },
                    function () {

                            jQuery.ajax({
                                url: "@Url.Action("BorrarObjetivo", "Objetivo")",
                                type: "POST",
                                data: JSON.stringify({ idObjetivo: info2.idObjetivo }),
                                dataType: "json",
                                contentType: "application/json; charset=utf-8",
                                success: function (data) {
                                    if (data.success) {

                                        // Recargar la tabla después de eliminar el proyecto
                                        tablaObjetivo.ajax.reload();
                                    } else {
                                        swal("Error", "Error al eliminar el objetivo: " + data.message, "error");
                                    }
                                }
                            });

                    });

            });




        });

    </script>
}